services:
  db:
    image: mariadb:11.4
    container_name: todo-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
    ports:
      - "3306:3306"

  api:
    image: ghcr.io/sacireda/todo-app-jdbc-spring-api:latest
    container_name: todo-api
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/todo
      SPRING_DATASOURCE_USERNAME: todo
      SPRING_DATASOURCE_PASSWORD: todo
